sonar.projectKey=PFA-TallerProyectos2
sonar.projectName=Sistema de Horarios Academicos (MERN)
sonar.projectVersion=1.0.0

sonar.sources=Backend,Frontend/src
sonar.exclusions=**/node_modules/**,**/coverage/**,Backend/public/**,Frontend/src/assets/**,**/*.test.*,**/__tests__/**,Frontend/src/mocks/**

sonar.tests=Backend/__tests__,Frontend/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.ts

sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info,Frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
